version: "2.4"
services:
  node:
    build: .
    environment:
      CONSOLE_PORT:
      STATSD_DOMAIN:
      STATSD_PORT:
    volumes:
      - type: volume
        source: freeton-rnode-config
        target: /etc/ton
      - type: volume
        source: freeton-rnode-data
        target: /node_db
    ports:
      - "${ADNL_PORT}:${ADNL_PORT}/udp"
      - "${CONSOLE_PORT}:${CONSOLE_PORT}"
    mem_limit: "${MEM_LIMIT}"
    memswap_limit: "${MEM_LIMIT}" # disables swap usage
    restart: always

  statsd:
    image: statsd/statsd
    volumes:
      - type: bind
        source: ./statsd/statsd-mapping.yaml
        target: /statsd-mappings/statsd-mapping.yaml
        read_only: true
    restart: always

volumes:
  freeton-rnode-config:
  freeton-rnode-data:

